account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'account'
urlpatterns = [
    path('', views.loginview, name='login'),
    path('register', views.registerview, name='register'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    
]

article/urls.py
from django.urls import path
from . import views
app_name= 'article'
urlpatterns = [
    path('', views.homeview, name='home'),
    path('<int:pk>/details', views.detailview, name='detail'),
    path('list', views.articlelist, name='list'),
    path('add-article', views.addarticle, name='add'),
    path('<int:pk>/update-article', views.updatearticle, name='update'),
    path('<int:pk>/delete-article', views.deletearticle, name='delete'),
    path('add-comment', views.addcomment, name='add-comment'),
    path('<int:pk>/remove-comment', views.removecomment, name='remove-comment'),
    path('update-comment', views.updatecomment, name='update-comment'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('articles/',include('article.urls')),
    path('tinymce/', include('tinymce.urls')),
]

from django.contrib import admin

admin.site.site_header = 'Articles Paradigm'                    # default: "Django Administration"
admin.site.index_title = 'Articles Paradigm'                 # default: "Site administration"
admin.site.site_title = 'Articles Paradigm adminsitration' # default: "Django site admin"

from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

article/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from tinymce.models import HTMLField
from django.template.defaultfilters import date
from django.utils.text import slugify

class Category(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category

class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_authors')
    body = HTMLField()
    excerpt = models.TextField(null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="pics", null=True, blank=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    @property
    def published(self):
        return '%s' % date(self.publish, "F d, Y")
    
    @property
    def comments(self):
        return Comment.objects.filter(post= self.id).order_by('-id')
    
    @property
    def related_posts(self):
        return Post.objects.filter(category = self.category).exclude(id=self.pk)[:6]
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='commentator')
    text = models.CharField(max_length=500, null=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    

account/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=63)
    password = forms.CharField(max_length=63, widget=forms.PasswordInput)

article/forms.py
from django import forms
from .models import Post
from tinymce.widgets import TinyMCE
class AddArticleForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["category",'title','body','excerpt','image']
        widgets = {
            'body': TinyMCE()
        }
        

account/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm
from django.contrib.auth import login, authenticate 
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse

def loginview(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Login in success.')
            return redirect('/articles')
            
        else:
            messages.error(request, 'Account does not exist.')
    return render(request, 'account/login.html', context={'form': form})

def registerview(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Account successfully created.')
            return redirect('account:login')
    else:
        form = UserCreationForm()
    return render(request, 'account/register.html', {'form': form})

article/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from .forms import AddArticleForm
from django.contrib import messages
from django.http import HttpResponseRedirect

def homeview(request):
    posts = Post.objects.all()
    return render(request,'article/home.html',{'posts':posts})

def detailview(request, pk):
    post = get_object_or_404(Post,id=pk)
    return render(request,'article/detail.html',{'post':post})

def articlelist(request):
    posts = Post.objects.filter(author =request.user)
    return render(request,'article/list.html',{'posts':posts})

def addarticle(request):
    form = AddArticleForm()
    if request.method == 'POST':
        form = AddArticleForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author=request.user
            obj.save()
            messages.success(request,'Article added.')
            return redirect('article:home')
    return render(request,'article/add.html',{'form':form})

def updatearticle(request,pk):
    post = get_object_or_404(Post,id=pk)
    form = AddArticleForm(instance=post)
    if request.method == 'POST':
        form = AddArticleForm( request.POST, request.FILES, instance = post)
        if form.is_valid():
            form.save()
            messages.success(request,'Article updated.')
            return redirect('article:list')
    return render(request,'article/update.html',{'form':form})

def deletearticle(request, pk):
    post = get_object_or_404(Post,id=pk)
    post.delete()
    messages.success(request,'Article removed.')
    return redirect('article:list')


def addcomment(request):
    if request.method == 'POST':
        text = request.POST.get('comment')
        id = request.POST.get('postid')
        post = get_object_or_404(Post,id=id)
        Comment.objects.create(user=request.user, text =text, post = post)
        messages.success(request,'Comment Posted.')
    return redirect(request.META.get('HTTP_REFERER'))

def removecomment(request,pk):
    comment = get_object_or_404(Comment,id=pk)
    comment.delete()
    messages.success(request,'Comment removed.')
    return redirect(request.META.get('HTTP_REFERER'))


def updatecomment(request):
    if request.method == 'POST':
        text = request.POST.get('comment')
        id = request.POST.get('commentid')
        obj = Comment.objects.get(id=id)
        obj.text = text
        obj.save()
        messages.success(request,'Comment Updated.')
    return redirect(request.META.get('HTTP_REFERER'))

templates/article/add.html
{% extends 'base.html' %}
{%load static%}
{% load bootstrap5 %}
{%block titleblock%}| Home{%endblock%}
{%block bodyblock%}


   <div class="col-lg-6 mx-auto">
    <h4 class="text-center p-3 mt-2">Add Article</h4>
    <form class="border p-3" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {% bootstrap_form form %}
        {{ form.media  }}

       <div class="d-flex justify-content-start mt-4">
        <button type="submit" class="btn btn-info">Publish</button>
       </div>
      </form>
   </div>


 {%endblock%}

templates/article/detail.html
{% extends 'base.html' %}
{%load static%}
{% load bootstrap5 %}
{%block titleblock%}| {{post.title}} {%endblock%}
{%block bodyblock%}

<div>
    <h3 class="mb-3">{{post.title}}</h3>
    <p><i>Written by <b>{{post.author.username}}</b> & published on {{post.published}} </i> </p>
    <img src="{{post.image.url}}" alt="image" class="img-fluid" width="100%" ><br>
    <div class="my-2">
        {{post.body|safe}}
    </div>
    <hr class="text-muted">
    <div>
       {% if request.user.is_authenticated %}
       <h5 class="my-2">Add your Comment</h5>
       <form class="d-flex" action="{%url 'article:add-comment'%}" method="post">
           {%csrf_token%}
           <input type="text" name="comment" maxlength="500" class="form-control me-3 " required>
           <input type="text" name="postid" value="{{post.id}}" hidden>
           <button type="submit" class="btn btn-info btn-sm ">Post Comment</button>
       </form>
       {%else%}
       <p class="my-5 text-muted">Login to add your comments.</p>
       {%endif%}

        <h5 class="my-2 mt-3">Posted Comments:</h5>
        {% for i in post.comments%}
        <div class="bg-light p-4 mb-2">
            <h5>{{i.user.username}} &nbsp; <span class="fw-light fs-6"> <i> {{i.created}}</i></span> </h6>
            <p>{{i.text}}</p>

            {% if request.user == i.user %}
            <a type="button" class="text-decoration-none" data-bs-toggle="modal" data-bs-target="#exampleModal{{i.id}}" >edit</a>
            <a class="ms-4 text-decoration-none" onclick="return confirm('Are you sure to remove your comment.')" href="{%url 'article:remove-comment' pk=i.id%}">remove</a>

            <!-- Edit Modal -->
<div class="modal fade" id="exampleModal{{i.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Edit Comment</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form class="d-flex" action="{%url 'article:update-comment' %}" method="post">
                {%csrf_token%}
                <input type="text" name="comment" value="{{i.text}}" maxlength="500" class="form-control me-3 " required>
                <input type="text" name="commentid" value="{{i.id}}" hidden>
        
           
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-info btn-sm">Save changes</button>
        </form>
          
        </div>
      </div>
    </div>
  </div>


            {%endif%}

        </div>
        {%empty%}
        <p class="p-3 text-center text-muted">No comments yet.</p>
        {%endfor%}


    </div>
    <hr class="text-muted">
    <div class="mt-5">
        <h4>You may also like:</h4><br>
        <div class="row mt-3">
            {% for y in post.related_posts %}
            <div class="col-lg-3">
                <a class="text-decoration-none text-dark " href="{%url 'article:detail' pk=y.id%}">
                    <img src="{{y.image.url}}" alt="image" class="img-fluid">
                    <h6 class="mt-2">{{y.title}}</h6>
                </a>

            </div>
            
               
          
            {%empty%}
            <p class="text-center my-5">No similar articles.</p>
            {%endfor%}
        </div>
        
    </div>

</div>


 {%endblock%}

templates/article/home.html
{% extends 'base.html' %}
{%load static%}
{% load bootstrap5 %}
{%block titleblock%}| Home{%endblock%}
{%block bodyblock%}


    <div class="row mt-2">
        {% for object in posts %}
        <div class="col-lg-4 mb-3 article">
           <a href="{% url 'article:detail' pk=object.id %}" class="text-decoration-none text-dark">
            <img src="{{object.image.url}}" class="mb-2 img-fluid"  alt="{{object.title}}">
            <h5>{{object.title}}</h5>
            <p class="fw-light">{{object.excerpt}}</p>
           </a>
        </div>
        {% empty %}
        <p class="text-center p-5 m-5">Nohing's here</p>
        {% endfor %}
    </div>
  </div>


 {%endblock%}

templates/article/list.html
{% extends 'base.html' %}
{%load static%}
{% load bootstrap5 %}
{%block titleblock%}| Home{%endblock%}
{%block bodyblock%}
<div class="col-lg-6 mx-auto">
    <h4 class="text-center mt-3 p-3">YOUR ARTICLES</h4><br><br>
    {% for object in posts %}
    <div class="row mb-3">
     <div class="col-md-10">
        <a href="{%url 'article:detail' pk=object.id%}" class="text-decoration-none text-dark">
           <h5>{{object.title}} &nbsp;
             <i title="approved & published" class="text-primary fa-solid fa-circle-check fs-6"></i>
           </h5>
           
           <p class="fw-light">{{object.excerpt}}</p>
          </a>
          <a type="button" href="{%url 'article:update' pk=object.id %}" class="btn btn-warning btn-sm " >Update</a >
          <a type="button" onclick="return confirm('Are you sure to remove this article? ')" href="{%url 'article:delete' pk=object.id %}" class="btn btn-danger btn-sm" >Remove</a >
         
     </div>
     <div class="col-md-2">
        <img src="{{object.image.url}}" height="100" class="mb-2" alt="{{object.title}}">
     </div>
      
    </div><hr class="text-light">
    {% empty %}
    <p class="text-center p-5 m-5">No articles yet.</p>
    {% endfor %}
   </div>


 {%endblock%}

templates/article/update.html
{% extends 'base.html' %}
{%load static%}
{% load bootstrap5 %}
{%block titleblock%}| Home{%endblock%}
{%block bodyblock%}


   <div class="col-lg-6 mx-auto">
    <h4 class="text-center p-3 mt-2">Update Article</h4>
    <form class="border p-3" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {% bootstrap_form form %}
        {{ form.media  }}

       <div class="d-flex justify-content-start mt-4">
        <button type="submit" class="btn btn-info">Update</button>
       </div>
      </form>
   </div>


 {%endblock%}

templates/base.html
<!doctype html>
{%load static%}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Articles Paradigm {%block titleblock%} {%endblock%}</title>
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
 <div class="container-fluid">
    <div class="container mt-2">
        
        <nav class="navbar navbar-expand-lg bg-info">
            <div class="container-fluid">
              <a class="navbar-brand h6" href="{%url 'article:home'%}">Articles Paradigm</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if request.user.is_authenticated %}
                    
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'article:list' %}">Your Articles</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'article:add'%}">Add Article</a>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          {{request.user.username}}
                        </a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{%url 'account:logout' %}">Logout</a></li>
                        </ul>
                      </li>
                      {% else%}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'account:login' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:register'%}">Register</a>
                  </li>
                  {%endif%}
                 
                 
                </ul>
               
              </div>
            </div>
          </nav>
          {%include 'messages.html'%}
  
      {% block bodyblock%}
      {% endblock %}
    </div>
</div>

      <footer>
        <p class="pt-5 text-center">&copy; articlesparadigm 2023</p>
      </footer>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

templates/messages.html
{% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="container-fluid px-0 mx-0  bg-success ">
                        <div class="container  px-4">
                    <div class="mt-alerts">
                        <div class="alert alert-dismissible fade show text-center text-white" role="alert">
                           {{message}}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        
                    </div>
                        </div>
                    </div>
                    {% endif %} {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
                    <div class="container-fluid px-0 mx-0 bg-danger">
                        <div class="container  px-4">
                    <div class=" mt-alerts ">
                        <div class="alert alert-dismissible fade show text-center text-white" role="alert">
                            {{message}} Sorry.
                            <button  type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}